---
title: "Сезон 2015-2016"
output: html_document
lang: russian
---




# Семинары по эконометрике

Эконометрика, факультет экономики, 3 курс, бакалавриат, 2015-2016, ВШЭ

Жаль, что в вышке пока нет системы коротких названий курсов. Вот я заранее застолбил EM301. Раз на третьем курсе, значит 300, а раз самый важный курс --- значит 1. :)

* Текущие оценки [гр. 131 и 132](https://docs.google.com/spreadsheets/d/1RARpbkzi0PYaIOBrpfm7SdQZ3rf382n_m9E1q-Jl-VE/pubhtml?gid=1970984948&single=true)
* [Подборка материалов](https://github.com/bdemeshev/em301/raw/master/metrics_exams/metrics_exams.pdf) (контрольные и немного теории)
* [Конспект семинаров 2014-2015](https://github.com/bdemeshev/em301/raw/master/2014/ec301_Alex_notes.pdf) с дополнениями (автор: Александр Левкун). 

## Компьютерное
* [Наборы данных](https://github.com/bdemeshev/em301/wiki/Datasets)
* [Про R](https://github.com/bdemeshev/em301/wiki/R)
* [LaTeX](https://github.com/bdemeshev/pr201/wiki/latex_examples) 
* [Весь используемый софт](https://github.com/bdemeshev/em301/wiki/Software)

## Логи семинаров (исследовательский поток)

#### Семинар 6. 13 октября 2015

* Задачи 2.13, 2.18, 2.24, 4.26.
* В R: оценка модели зависимости стандартизированного показателя плодовитости от количества мужчин, занятых в сельском хозяйстве, и доли католического населения.

#### Семинар 5. 06 октября 2015
* Проверка несмещенности оценок (2.6). Дисперсия и свойства оценки $\small{\hat\beta_2}$ (2.17).
* Д.з.: с прошлого семинара (4.16, 4.21, 4.22, 4.25, 4.26, 1.15, 1.20) + минимум (Белая Роза) + дополнительные задачи (Алая Роза).
* Белая Роза: 2.8, 2.13, 2.18, 2.24, 2.28.
* Алая Роза: 2.32, 2.34, 2.36, 2.42.

#### Семинар 4. 29 сентября 2015

* Упражнение по линейной алгебре. Математическое ожидание и ковариационная матрица вектора, аналогия с одномерным случаем. Предположения для неслучайного X. Мета-мега-матрица.
* Д.з.: досчитать все математические ожидания и ковариации в мета-мега-матрице.

#### Семинар 3. 22 сентября 2015

* Задача про матрицу из контрольной.
* МНК. Прогнозирование с двумя объясняющими переменными. Геометрическая интерпретация.
* Д.з.: уметь рисовать картинку; найти как можно больше прямоугольных треугольников и выписать для них теоремы Пифагора в двух вариантах (с квадратами длин и с суммами). Сдавать не нужно.
* Как сдавать любое д.з. в электронном виде: по почте отправить файлы `.Rnw` и `.pdf`, файл `.pdf` принести распечатанным. В теме письма обязательно указать EM301 с каким-нибудь пояснением (например, EM301 Домашнее задание 3). Сами файлы называть только английскими буквами, без пробелов, в названии как-нибудь отразить фамилию.

#### Семинар 2. 15 сентября 2015

* Контрольная работа 1. [Вспомнить всё!!!](https://github.com/bdemeshev/em301/raw/master/2015/kr_01_recall_all/kr_01_recall_all.pdf) Время —-- 1 час.

#### Семинар 1. 08 сентября 2015
* МНК. Модели зависимости роста от веса и погоды на улице (без параметра).
* [Оценка моделей](https://github.com/bdemeshev/em301/blob/master/2015/sem_01.R) с помощью МНК в R.
* Темы Контрольной работы 1: скалярное произведение и его связь с косинусом угла, т. Пифагора, т. о трех перпендикулярах; проверка гипотезы о среднем, уровень значимости, p-value, доверительные интервалы; свойства м.о., дисперсии, условная вероятность; умножение, обращение, транспонирование матриц, определитель и след матрицы, их связь с собственными значениями; det(AB), tr(AB).
* Д.з.: установить [R/Rstudio/Latex](https://github.com/bdemeshev/em301/wiki/R); выслать два файла (`.Rnw` и `.pdf`) с пятью фактами о себе и картинкой до 10:40 22 сентября, распечатанным сдать только `.pdf` файл.
* Пример домашнего [задания от Хрюши](https://github.com/bdemeshev/em301/raw/master/2015/ht_01_hrusha/ht_01_hrusha.zip). Можно разархивировать файл, открыть `.Rnw` в R-studio, нажать "compile pdf", должен получиться готовый pdf-файл.

## Лекции

* [Краткое содержание](http://bdemeshev.github.io/em301/log_lectures_2015.html) лекций

## Литература и ссылки

* [Официальная программа](http://www.hse.ru/edu/courses/150659374.html) курса
* Программа [моей мечты](https://github.com/bdemeshev/em301/wiki/dream_econometrics)
* Секретная [формула](https://github.com/bdemeshev/em301/raw/master/em301_grade_system.txt) расчёта оценки
* Логи семинаров [2012-2013](https://github.com/bdemeshev/em301/wiki/wiki_2012_2013), [2013-2014](https://github.com/bdemeshev/em301/wiki/wiki_2013_2014), [2014-2015](http://bdemeshev.github.io/em301/index_2014_2015.html)
* Видео-записи семинаров [2013-2014](https://vimeo.com/album/2517754) 


### Правильное отношение к научным исследованиям:
* Аркадий и Борис Стругацкие, [Понедельник начинается в субботу](http://www.e-reading.club/book.php?book=55060)
* Douglas Adams, Hitchhiker's guide to the galaxy, [рус](http://royallib.com/book/adams_duglas/putevoditel_volnogo_strannika_perevod_vbakanova.html), [eng](http://www.ebooktrove.com/top_ten/DouglasAdams_TheHitchhikerTrilogy_5Books1ShortStory.pdf)

### Конспекты вышкинского курса
* [Заметки Ивана Назарова](https://github.com/bdemeshev/em301/raw/master/hse_notes/nazarov,%20emetrix-summary.pdf)
* [Конспект Андрея Костырки лекций Г.Г. Канторовича](https://github.com/bdemeshev/em301/raw/master/hse_notes/kantorovich,%20lectures%20by%20kostyrka.pdf)
* [Конспект Андрея Костырки семинаров А.А. Мамонтова](https://github.com/bdemeshev/em301/raw/master/hse_notes/mamontov,%20seminars%20by%20kostyrka.pdf)


### Эконометрика, free books
* Michael Creel, [Econometric lecture notes](http://econpapers.repec.org/paper/aubautbar/575.03.htm): graduate level
* Bruce Hansen, [Econometrics](http://www.ssc.wisc.edu/~bhansen/econometrics/): graduate level
* John Stachurski, [First course on econometric theory](http://johnstachurski.net/_downloads/et.pdf): graduate level (?)
* Breheny, [Applied Statistical Modeling for Medicine and Public Health](http://web.as.uky.edu/statistics/users/pbreheny/764-F11/index.html) Замечательно изложены методы "за пределами" простой регрессии с примерами на R.
* Wolter Sosa-Escudero, [Econometric analysis](http://www.econ.uiuc.edu/~wsosa/econ507/index.htm). Продвинутый магистерский курс с кучей интересных материалов внизу страницы.
* Dolf Schluter, [Quantitative methods in ecology and evolution](https://www.zoology.ubc.ca/~bio501/R/) Курс по статистике для магистров биологов. Хорошая подборка статей по статистике, хорошее введение в R. 
* Faraway, [Practical regression and ANOVA using R](http://cran.r-project.org/doc/contrib/Faraway-PRA.pdf) Гетероскедастичность, мультиколлинеарность, метод главных компонент, Ridge regression, ANOVA.
* Никита Артамонов, [Введение в эконометрику](http://img1.liveinternet.ru/images/attach/c/2//3833/3833271_econometrics.pdf)
* Кирилл Фурманов, [Сборник задач на личной страничке](http://www.hse.ru/org/persons/503346)
* Стренг, [Линейная алгебра](http://elibrary.bsu.az/kitablar/1022.pdf), древний, но очень удачный учебник по линейной алгебре
* A. Ian McLeod, Hao Yu, Esam Mahdi, [Time Series Analysis with R](http://www.stats.uwo.ca/faculty/aim/tsar/), замечательный обзор пакетов R по временным рядам с примерами кода. Заодно там рядом по ссылке толстая поваренная книга (777 страниц) по временным рядам.

### Мелочи:
* Теорема Фриша-Вау: [wikipedia](http://en.wikipedia.org/wiki/Frisch–Waugh–Lovell_theorem), [simple proof](http://mlovell.web.wesleyan.edu/Publications/SPFWLTheorem.pdf), [geometry](http://www.depeco.econo.unlp.edu.ar/doctrab/doc29.pdf)
* Вывод [критерия BIС](http://nscs00.ucmerced.edu/~nkumar4/BhatKumarBIC.pdf)
* Неплохое объяснения [эффекта возвращения к среднему](http://avva.livejournal.com/2426970.html)
* Преобразования [Бокса-Кокса, Ю-Джонсона](http://www.ime.usp.br/~abe/lista/pdfm9cJKUmFZp.pdf)
* История regression fallacy --- Maddala, Intro to econometrics, [p. 104](https://github.com/bdemeshev/em301/raw/master/useful_stuff/Maddala_regression_word.pdf)
* Breheney, [Ridge regression](http://web.as.uky.edu/statistics/users/pbreheny/764-F11/notes/9-1.pdf)
* Гид по [прогнозированию рядов для чайников](http://people.duke.edu/~rnau/411fcst.htm)
* Мелкие [ловушки с рядами в R](http://www.stat.pitt.edu/stoffer/tsa3/Rissues.htm)
* Матричное дифференциирование: [Herman Kamper](http://www.kamperh.com/notes/kamper_matrixcalculus13.pdf), [Thomas P. Minka](http://research.microsoft.com/en-us/um/people/minka/papers/matrix/minka-matrix.pdf)
* Графики временных рядов: [примеры](http://timelyportfolio.github.io/rCharts_time_series/history.html), [пакет dygraphs](https://rstudio.github.io/dygraphs/index.html)


### Форумы, где спросить совет...
* [stats.stackexchange.com](http://stats.stackexchange.com) - по статистике
* [maths.stackexchange.com](http://maths.stackexchange.com) - по студенческой математике
* [stackoverflow.com](http://stackoverflow.com) - по программированию
* [tex.stackexchange.com](http://tex.stackexchange.com) - по Теху
 


### Прочие книжки

Можно купить или найти в [чёрном](http://gen.lib.rus.ec/)-[чёрном](http://bookzz.org/)-[чёрном](http://sci-hub.org/) Интернете:

* Freedman, Statistical models
* Seber, Linear Regression Analysis, хорошо изложена матричная сторона дела. Есть перевод первого издания на русский. 


## Лицензия
Созданные мной для данного курса материалы распространяются по лицензии [Creative Commons Attribution-NonCommercial-ShareAlike](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.ru)
