---
title: "Лекции 2015-2016"
output: html_document
lang: russian
---

[Конспект Андрея Костырки лекций Г.Г. Канторовича](https://github.com/bdemeshev/em301/raw/master/hse_notes/kantorovich,%20lectures%20by%20kostyrka.pdf) (2011-2012)

###Темы лекций

####Лекция 11. 26 ноября 2015

Теорема Гаусса--Маркова для стохастических регрессоров (продолжение). Условие экзогенности. Условие предопределённости. Теория перманентного дохода. Метод инструментальных переменных.


####Лекция 10. 19 ноября 2015

Стохастические регрессоры. Условное математическое ожидание и его свойства. Условная дисперсия и условная ковариация, их свойства. Теорема Гаусса--Маркова для стохастических регрессоров.

####Лекция 9. 12 ноября 2015

Дамми--переменные. Дифференциация в трудовой карьере (по диплому, по трудовому стажу, по расе). Ошибка дамми--переменных. Тест Чоу. Сезонность и сезонные данные.

####Лекция 8. 05 ноября 2015

Экспоненциально убывающая функция спроса. Эластичность спроса по цене. The Box--Cox transformation. Zarembka scaling. Модели в обратных переменных. Закон Энгеля. Кривая Филлипса. Полиномиальная регрессия. Уравнение Минцера.

####Лекция 7. 22 октября 2015

Нормальный вектор. Проверка гипотез: о значимости признаков (всех и части), об адекватности регрессии. Проверка общей линейной гипотезы.

####Лекция 6. 15 октября 2015

Множественная регрессия. Теорема Гаусса--Маркова для множественной регрессии.

####Лекция 5. 08 октября 2015

P--значение. Проверка гипотез о значимости коэффициентов. Пример в excel. Коэффициент <i>R<sup>2</sup></i>. Тест адекватности регрессии. 
<br />F--отношение. Распределение Фишера. Дисперсионный анализ (ANOVA). Выборочный коэффициент корреляции. Регрессия без свободного члена. Переход к центрированным и нормированным переменным.

####Лекция 4. 01 октября 2015

Вопрос о состоятельности оценок МНК. Классическая линейная регрессия. Доверительные интервалы и проверка гипотез.

####Лекция 3. 24 сентября 2015

Свойства оценок МНК. Теорема Гаусса--Маркова.

####Лекция 2. 17 сентября 2015

Диаграмма рассеяния. Регрессия. МНК. Система нормальных уравнений МНК. Свойства коэффициентов. Геометрическая интерпретация.

####Лекция 1. 10 сентября 2015

Что такое эконометрика и где она используется. Типы данных. Примеры открытых баз данных. Этапы эконометрического исследования. Модель. Методы оценивания. Тестирование оцененной модели. Статистические пакеты.




